### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

### ISSUE THREAD

**Issue by byungjinku** [chequanghuy/TwinLiteNet#12]
Hello I wanted to test best.engine model on AGX Orin but I've got this error:

[02/27/2024-12:24:03] [TRT] [I] Loaded engine size: 2 MiB
[02/27/2024-12:24:03] [TRT] [E] 1: [runtime.cpp::parsePlan::314] Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.)
Traceback (most recent call last):
  File "/home/bjku/TwinLiteNet/test_trt.py", line 68, in <module>
    trt=TRT('best.engine')
  File "/home/bjku/TwinLiteNet/test_trt.py", line 45, in __init__
    self.context = model.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

Sombody could help me ?

**Comment by harrylal** [comment]
Can you please verify whether you using different versions of TRT for constructing the engine compared to deserializing it?  are you using  different devices for building and deserializing the engine?
